---
repos:
  - hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: pretty-format-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
  - hooks:
      - args:
          - '--config=pyproject.toml'
        id: black
    repo: https://github.com/psf/black
    rev: 22.10.0
  - hooks:
      - id: pyright
    repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.339
  - hooks:
      - id: isort
        name: isort (python)
    repo: https://github.com/pycqa/isort
    rev: 5.12.0
