repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: pretty-format-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - '--config=pyproject.toml'
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.339
    hooks:
    - id: pyright
